### PR TITLE
Add FCEB and Enrolled Column to stakeholders.csv

### LINKED ISSUE #110: Add FCEB & Enrollment Column to stakeholders.csv
# 💡 Summary #

Please add a FCEB and Enrolled column to the stakeholders.csv after the cyhy-stakeholder alias is called.

## Motivation and context ##

Internal stakeholders would like to know agencies identified as FCEB and when agencies were enrolled for the service. 

## Implementation notes ##

Please provide details for implementation, such as:

- Add a column to the stakeholders.csv denoting FCEB status.
- Add a column to the stakeholders.csv with the enrolled status

Specific stakeholders.py code found here:  https://github.com/cisagov/cyhy-reports/blob/dc75e103292137bcfef1ef3bd6464b4e9817e418/cyhy_report/stakeholders/stakeholders.py

## Acceptance criteria ##

- [x] New Column named FCEB with Yes/No for FCEB status
- [x] New Column named Enrolled with date of enrollment

### PR DESCRIPTION
**Pull request by KeithBonesJr**
#  #

## 🗣 Description ##
Adds FCEB and Enrolled column to stakeholders.csv file generated by cyhy-stakeholders alias. 

## 💭 Motivation and context ##

Fixes https://github.com/cisagov/cyhy-reports/issues/110 

## 🧪 Testing ##
1. Pulled down and built latest cyhy-reports repository from https://github.com/cisagov/cyhy-reports
2. Made and saved changes
3. Ran **docker build -t cisagov/cyhy-reports .** within my local cyhy-reports environment
4. Ran **cyhy-stakeholders > stakeholders.csv**
5. Verified the existence and accuracy of the newly added FCEB and Enrolled column in the stakeholders.csv file

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] All relevant type-of-change labels have been added.
- [X] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [X] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [X] All new and existing tests pass.

## ✅ Post-Merge checklist ##

- [] Notify team to update local cyhy-reports image

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by jsf9k — APPROVED** [review]
This looks good to me.

**Review by jsf9k — APPROVED** [review]

**Review by michaelsaki — APPROVED** [review]

**Comment by dav3r** [comment]
@KeithBonesJr In the PR description above, when you wrote "Deploy this change to Production" (Post-merge checklist), were you referring to creating a new Docker image with this change and distributing it to the team?  If so, for clarity in future PRs, you can just write something to that effect.  If you meant something else, please let us know.

**Comment by KeithBonesJr** [comment]
@dav3r understood! I'll remove that line. We can just pull latest cyhy-report, no image needed.

**Comment by dav3r** [comment]
For future PRs, I still think it's worthwhile for you to include some kind of post-merge checklist item along the lines of informing your team so that they know to pull in the latest change and rebuild their local Docker image.

**Pull request merged**
