### PR TITLE
Add "protocol" column to findings.csv

### PR DESCRIPTION
**Pull request by KeithBonesJr**
#  #

## 🗣 Description ##

This PR:

- Adds a new column to the findings.csv named "protocol" for vulnerability scanning reports.

## 💭 Motivation and context ##

This PR contains the changes requested in https://github.com/cisagov/cyhy-system/issues/93 

## 🧪 Testing ##

I built a local Docker image with these changes and then used that to generate a variety of test reports. I verified the column existed within the findings.csv file. This matches the exact ask for the improvement.

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] All relevant type-of-change labels have been added.
- [X] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [X] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [X] All new and existing tests pass.

## ✅ Post-merge checklist ##
- [x] Deploy this change to Production.

### CODE REVIEW

**Comment by KeithBonesJr** [comment]
Hmm wasn't able to add reviewers nor labels this time around.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍

**Comment by dav3r** [comment]
@KeithBonesJr Did you verify that the new field correctly appears in the CSV for both anonymized and sub-org reports (the other branches of that `if` statement in `__generate_findings_attachment()`)?

**Review by dv4harr10 — APPROVED** [review]

**Comment by KeithBonesJr** [comment]
@dav3r  only verified for main VS report. Jeff should be in within the next hour or so. I'll generate a suborg and  anonymized report as well. I have my env setup however because the "pip" command is no longer available for me, I wasn't able to build the repo and hence am at the mercy of my teammates.

**Comment by KeithBonesJr** [comment]
@dav3r tested for the suborg and anonymized report. Good to go.

**Pull request merged**
